name: Debug SECRET CHECK (temporary)

on:
  workflow_dispatch:

permissions:
  actions: read

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID || 'fail' }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET || 'fail' }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL || 'fail' }}
    steps:
      - name: Masked Google Client ID (safe)
        run: |
          if [ -z "${GOOGLE_CLIENT_ID}" ]; then
            echo "GOOGLE_CLIENT_ID is missing or empty"
            exit 1
          fi
          s="${GOOGLE_CLIENT_ID}"
          prefix=${s:0:4}
          suffix=${s: -4}
          echo "GOOGLE_CLIENT_ID masked: ${prefix}...${suffix}"
        shell: bash
      - name: Show presence of other secrets
        run: |
          echo "GOOGLE_CLIENT_SECRET present: $( [ -n \"${GOOGLE_CLIENT_SECRET}\" ] && echo yes || echo no )"
          echo "WEBHOOK_URL present: $( [ -n \"${WEBHOOK_URL}\" ] && echo yes || echo no )"
        shell: bash
